url: "https://hackingux.design" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "HackingUX" # the name of your site, e.g. ACME Corp.
